### ISSUE TITLE
Hibernation should be opt-in instead of opt-out

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/online-hibernation#57]
It looks like this project works by having a fixed list of namespaces to exclude from
Idling.   This seems error prone.

Rather than maintain a fixed opt-in/opt-out list, why not have the function key off a namespace label, and label all projects that are subject to hibernation?

This lets us more easily debug the system in production.  The new-project request would then auto apply this label in free-tier.  We could have a one-time migrate step to add the label to existing projects that require it.

@eparis @smarterclayton - input appreciated.

**Comment by smarterclayton** [comment]
Fixed list of namespaces is prone to failure.

**Comment by derekwaynecarr** [comment]
An annotation would work as well.

I just prefer we require a field to hibernate rather than require a field to not hibernate.  The latter is error prone as the project evolves.

**Comment by damemi** [comment]
@derekwaynecarr We have actually been considering doing the opposite, and offering an annotation to *exclude* projects from hibernation. This would make sense because the list of namespaces subject to hibernation will always far outweigh the list of excluded namespaces, and it also puts the control of excluding a namespace directly in the hands of its relevant owners with permission to do that (since normal users can't edit project annotations). It's basically the same approach though.

**Comment by sallyom** [comment]
@damemi we'll get together, implement this today-ish.  The fixed-list was always meant to be temporary, we need to get rid of that asap. @derekwaynecarr 's  label via project-request with a one-time add-label-to-existing step seems best to me.  I can fit this in this week, it needs to happen :+1:

**Comment by sallyom** [comment]
https://github.com/openshift/online/pull/1748  adds the label to the project-request template, for starter-tier only
